DROP TABLE IF EXISTS MANY_TO_MANY;
GO

DROP TABLE IF EXISTS OSOBA;
GO

DROP TABLE IF EXISTS MIEJSCE_PRACY;
GO


CREATE TABLE MIEJSCE_PRACY (
	ID int IDENTITY(0,1) PRIMARY KEY,
	WorkspaceName [nvarchar](150) NOT NULL,
	);
GO

INSERT INTO MIEJSCE_PRACY VALUES('ADC'), ('CVB');
GO

SELECT * FROM MIEJSCE_PRACY;
GO

CREATE TABLE OSOBA (
	ID int IDENTITY(0,1) PRIMARY KEY,
	FirstName [nvarchar](150) NOT NULL,
	LastName [nvarchar](150) NOT NULL,
	);
GO

INSERT INTO OSOBA VALUES('Adrian', 'Czuchaj'), ('Jan', 'Kowalski'), ('Marcin', 'Malinowski');

SELECT * FROM OSOBA;
GO

CREATE TABLE MANY_TO_MANY(
	ID int IDENTITY(0,1) PRIMARY KEY,
	ID_osoba int FOREIGN KEY REFERENCES OSOBA(ID),
	ID_praca int FOREIGN KEY REFERENCES MIEJSCE_PRACY(ID),
	);

INSERT INTO MANY_TO_MANY VALUES(0, 0), (1, 1), (1, 0), (2, 1);

SELECT OSOBA.FirstName, OSOBA.LastName, MIEJSCE_PRACY.WorkspaceName
FROM MANY_TO_MANY 
JOIN MIEJSCE_PRACY 
ON MIEJSCE_PRACY.ID = MANY_TO_MANY.ID_praca
JOIN OSOBA
ON OSOBA.ID = MANY_TO_MANY.ID_osoba
GO